version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: recipe-crawler-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: recipe_crawler
      MYSQL_USER: recipe_user
      MYSQL_PASSWORD: recipe_password
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    container_name: recipes-public-postgres
    restart: always
    environment:
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_password
      POSTGRES_DB: recipes_public
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
  postgres-data:
