export const TAG_BLACKLIST = new Set([
    // Generic / meaningless
    'recipe',
    'recipes',
    'food',
    'meal',
    'meals',
    'dish',
    'dishes',
    'cooking',
    'cook',
    'homemade',
    'home',
    'kitchen',
    'style',

    // Subjective / emotional
    'easy',
    'simple',
    'quick',
    'fast',
    'tasty',
    'delicious',
    'yummy',
    'amazing',
    'awesome',
    'perfect',
    'perfection',
    'best',
    'better',
    'ultimate',
    'favorite',
    'favorites',
    'classic',
    'beautiful',
    'delightful',
    'comforting',
    'comfort',
    'comfortfood',
    'healthyish',
    'fun',
    'supreme',
    'nostalgic',
    'forgiving',

    // Time-related or speed implications
    'minute',
    'minutes',
    'hour',
    'hours',
    'day',
    'weeknight',
    'weekday',
    'weekend',
    'fast',
    'quickly',
    'speedy',
    'time',
    '15-minute',
    '30-minute',
    '5-minute',

    // Ingredient count / number-based gimmicks
    '2-ingredient',
    '3-ingredient',
    '4-ingredient',
    '5-ingredient',
    'two-ingredient',
    'three-ingredient',
    'four-ingredient',
    'five-ingredient',
    'one-ingredient',
    'single-ingredient',

    // Brands / commercial names
    'trader',
    "joe's",
    'oreo',
    'snickers',
    'nestle',
    'hershey',
    'ragu',
    'kraft',
    'riverview',
    'restaurant',
    'bar',
    'café',
    'starbucks',
    'mcdonalds',
    'costco',

    // Abstract / non-food concepts
    'childhood',
    'memories',
    'story',
    'route',
    'modernized',
    'inspired',
    'influence',
    'influenced',
    'tradition',
    'times',
    'supreme',
    'simplelife',
    'perfection',

    // Redundant / filler
    'easyrecipe',
    'easydinner',
    'quickmeal',
    'quickdinner',
    'familyfriendly',
    'family-favorite',
    'familyrecipe',
    'homecooked',
    'homestyle',
    'homemade-dessert',
    'homemade-snack',

    // Irrelevant adjectives
    'lazy',
    'laziness',
    'weekday',
    'weekend',
    'poolside',
    'holiday',
    'festive',
    'seasonal',
    'springtime',
    'summertime',
    'wintertime',
    'fall',
    'autumn',

    // Meta / platform or noise
    'viral',
    'trend',
    'tiktok',
    'instagram',
    'youtube',
    'reel',
    'shorts',
    'post',

    // Sensory descriptors (avoid overgeneralized taste)
    'savory',
    'mild',
    'flavorful',
    'fruity',
    'buttery',
    'crunchy',
    'crispy',
    'moist',
    'juicy',
    'rich',
    'smooth',
    'zesty',
    'bold',

    // Meta-data related
    'new',
    'latest',
    'modern',
    'retro',
    'old-fashioned',
    'traditional',
    'classic',
    'updated',
    'version',

    // Any residual catch-alls
    'quick-and-easy',
    'simple-and-fast',
    'good',
    'great',
    'nice',
    'lovely',
]);
